FROM node:20-alpine3.21

# Patch OS packages and the base-image-bundled npm to clear known HIGH/CRITICAL vulns
RUN apk upgrade --no-cache && npm install -g npm@latest

WORKDIR /usr/src/app

COPY ["*.json", "yarn.lock", "./"]

RUN yarn && yarn cache clean

COPY . .
RUN rm -rf ./views_uid2
RUN rm -rf ./public/locales_uid2
RUN mv ./views_euid ./views
RUN mv ./public/locales_euid ./public/locales
RUN rm ./public/images/UID2* ./public/images/unifiedid2*

RUN yarn build
RUN yarn lint

ENV ID_TYPE EUID

EXPOSE 3000
EXPOSE 9082
CMD [ "./build/bin/www" ]

