FROM node:20.11.0-alpine3.18

WORKDIR /usr/src/app

COPY ["*.json", "yarn.lock", "./"]

RUN yarn

COPY . .
RUN rm -rf ./views_uid2
RUN rm -rf ./public/locales_uid2
RUN mv ./views_euid ./views
RUN mv ./public/locales_euid ./public/locales
RUN rm ./public/images/UID2* ./public/images/unifiedid2*

RUN yarn build
RUN yarn lint

ENV ID_TYPE EUID

EXPOSE 3000
EXPOSE 9082
CMD [ "./build/bin/www" ]

