FROM node:14.17.3-alpine3.11

WORKDIR /usr/src/app

COPY ["*.json", "yarn.lock", "./"]

RUN yarn

COPY . .
RUN rm -rf ./views_euid
RUN rm -rf ./public/locales_euid
RUN mv ./views_uid2 ./views
RUN mv ./public/locales_uid2 ./public/locales
RUN rm ./public/images/EUID.png

RUN yarn build

ENV ID_TYPE UID2

EXPOSE 3000
EXPOSE 9082
CMD [ "./build/bin/www" ]

