FROM node:20-alpine3.21

# Patch OS packages and the base-image-bundled npm to clear known HIGH/CRITICAL vulns
RUN apk upgrade --no-cache && npm install -g npm@latest

WORKDIR /usr/src/app

COPY ["*.json", "yarn.lock", "./"]

RUN yarn && yarn cache clean

COPY . .
RUN rm -rf ./views_euid
RUN rm -rf ./public/locales_euid
RUN mv ./views_uid2 ./views
RUN mv ./public/locales_uid2 ./public/locales
RUN rm ./public/images/EUID.png

RUN yarn build
RUN yarn lint

ENV ID_TYPE UID2

EXPOSE 3000
EXPOSE 9082
CMD [ "./build/bin/www" ]

