name: Build and Test
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      # Check out repository $GITHUB_WORKSPACE
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: setup yarn
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: lint lockfile (single registry host + https)
        run: npx --yes lockfile-lint --path yarn.lock --type yarn --allowed-hosts npm --validate-https
      - name: build
        run: yarn build
      - name: lint 
        run: yarn lint
      - name: test
        #TODO Remove this when we have tests
        run: yarn test --passWithNoTests
      - name: Vulnerability Scan
        uses: IABTechLab/uid2-shared-actions/actions/vulnerability_scan@v3
        with:
          scan_type: 'fs'
