name: Docker
on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_UID2: iabtechlab/uid2-tcportal
  IMAGE_NAME_EUID: iabtechlab/euid-tcportal

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get Package Version
        id: version
        run: |
          echo "::set-output name=package_version::$(cat package.json | jq -r '.version')"
      - name: Log in to the Container registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker (UID2)
        id: meta-uid2
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_UID2 }}
          tags: |
            type=sha,prefix=${{ steps.version.outputs.package_version }}-,format=short
      - name: Build and push Docker image (UID2)
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          file: Dockerfile_uid2
          push: true
            #tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:
          tags: ${{ steps.meta-uid2.outputs.tags }}
          labels: ${{ steps.meta-uid2.outputs.labels }}
      - name: Extract metadata (tags, labels) for Docker (EUID)
        id: meta-euid
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_EUID }}
          tags: |
            type=sha,prefix=${{ steps.version.outputs.package_version }}-,format=short
      - name: Build and push Docker image (EUID)
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: .
          file: Dockerfile_euid
          push: true
            #tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:
          tags: ${{ steps.meta-euid.outputs.tags }}
          labels: ${{ steps.meta-euid.outputs.labels }}          
